INSERT INTO USERS (USER_ID, PASSWORD, ROLE) VALUES ('user1', '$2a$10$a0mJYRqmV2lqmbYIYXwZgeHZT98B85zcvlCgm1gMUYWs84XvdgsJa', 'MASTER');
INSERT INTO USERS (USER_ID, PASSWORD, ROLE) VALUES ('admin1', '$2a$10$a0mJYRqmV2lqmbYIYXwZgeHZT98B85zcvlCgm1gMUYWs84XvdgsJa', 'ADMIN');


INSERT INTO API_PERMISSIONS
(ID, ROLES, METHODS, PATH, DESCRIPTION)
VALUES(1, 'MASTER', 'GET', '/h2-console/**', 'h2 DB 조회');
INSERT INTO API_PERMISSIONS
(ID, ROLES, METHODS, PATH, DESCRIPTION)
VALUES(2, 'MASTER', 'POST', '/h2-console/**', 'h2 DB 수정');
INSERT INTO API_PERMISSIONS
(ID, ROLES, METHODS, PATH, DESCRIPTION)
VALUES(3, 'MASTER', 'PUT', '/api/users/**', '유저 정보 수정');
INSERT INTO API_PERMISSIONS
(ID, ROLES, METHODS, PATH, DESCRIPTION)
VALUES(4, 'MASTER,ADMIN', 'GET', '/api/user', '유저 리스트 조회');
INSERT INTO API_PERMISSIONS
(ID, ROLES, METHODS, PATH, DESCRIPTION)
VALUES(5, 'MASTER', 'PUT,DELETE', '/api/permission/**', 'API 권한 관리 수정,삭제');
INSERT INTO API_PERMISSIONS
(ID, ROLES, METHODS, PATH, DESCRIPTION)
VALUES(6, 'MASTER', 'POST', '/api/save-permission', 'API 권한 관리 등록');
INSERT INTO API_PERMISSIONS
(ID, ROLES, METHODS, PATH, DESCRIPTION)
VALUES(8, 'MASTER,ADMIN', 'GET', '/api/permissions', 'API 권한 리스트 조회');

