INSERT INTO USERS (USER_ID, PASSWORD, ROLE) VALUES ('user1', '$2a$10$a0mJYRqmV2lqmbYIYXwZgeHZT98B85zcvlCgm1gMUYWs84XvdgsJa', 'MASTER');
INSERT INTO USERS (USER_ID, PASSWORD, ROLE) VALUES ('admin1', '$2a$10$a0mJYRqmV2lqmbYIYXwZgeHZT98B85zcvlCgm1gMUYWs84XvdgsJa', 'ADMIN');

INSERT INTO API_PERMISSIONS (ROLES, METHODS, PATH) VALUES ('MASTER', 'GET', '/h2-console/**');
INSERT INTO API_PERMISSIONS (ROLES, METHODS, PATH) VALUES ('MASTER', 'POST', '/h2-console/**');
INSERT INTO API_PERMISSIONS (ROLES, METHODS, PATH) VALUES ('MASTER', 'PUT', '/api/users/**');
INSERT INTO API_PERMISSIONS (ROLES, METHODS, PATH) VALUES ('MASTER', 'GET', '/api/user');

